### ISSUE TITLE
[Bug] Android build error on v1.1.2

### ISSUE THREAD

**Issue by samuelcecilio** [team-telnyx/flutter-voice-sdk#176]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x] Other

**SDK Version**
telnyx_webrtc: ^1.1.2 (works on 1.1.0)

**Describe the bug**
Build error on android, using flutter v3.27.4 and Java 17.

**Logs**

```
/home/builder/.pub-cache/hosted/pub.dev/flutter_webrtc-0.13.1+hotfix.1/android/src/main/java/com/cloudwebrtc/webrtc/SurfaceTextureRenderer.java:118: error: <anonymous com.cloudwebrtc.webrtc.SurfaceTextureRenderer$1> is not abstract and does not override abstract method onSurfaceDestroyed() in Callback
            new TextureRegistry.SurfaceProducer.Callback() {
                                                           ^
/home/builder/.pub-cache/hosted/pub.dev/flutter_webrtc-0.13.1+hotfix.1/android/src/main/java/com/cloudwebrtc/webrtc/SurfaceTextureRenderer.java:124: error: method does not override or implement a method from a supertype
```

**Comment by Oliver-Zimmerman** [comment]
update to 2.0.0 or higher, thanks

**Comment by arthurgiani** [comment]
I'm facing the same issue as @samuelcecilio using the same bumped version. Maybe this issue needs to be reopened
