### ISSUE TITLE
[Bug] Web build error on v1.2.0, v1.1.3 and v2

### ISSUE THREAD

**Issue by samuelcecilio** [team-telnyx/flutter-voice-sdk#177]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x] Other

**SDK Version**
telnyx_webrtc: ^1.1.3 and higher (works on 1.1.2 and lower)

**Describe the bug**
Build error on web, flutter 3.27.4

**Logs**
```
Compiling lib/src/widgetbook.dart for the Web...                
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
/root/.pub-cache/hosted/pub.dev/telnyx_webrtc-1.2.0/lib/call.dart:283:21:
Error: The setter 'onCallQualityChange' isn't defined for the class 'Peer'.
- 'Peer' is from 'package:telnyx_webrtc/peer/web/peer.dart' ('/root/.pub-cache/hosted/pub.dev/telnyx_webrtc-1.2.0/lib/peer/web/peer.dart').
    peerConnection?.onCallQualityChange = callQualityMetricsHandler;
                    ^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/flutter/bin/cache/dart-sdk/bin/dart /codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/82bd5b7209295a5b7ff8cae0df96e7870171e3a5/ --native-null-assertions --no-source-maps -o /codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/packages/commons/ic_design_system/design_system_example/.dart_tool/flutter_build/afe3cf08bb00154e9be4b6b3d3f4f436/app.dill --packages=/codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/packages/commons/ic_design_system/design_system_example/.dart_tool/package_config.json --cfe-only /codebuild/output/src2687725195/src/github.com/iConnections/flutter_mobile_app_V2/packages/commons/ic_design_system/design_system_example/.dart_tool/flutter_build/afe3cf08bb00154e9be4b6b3d3f4f436/main.dart
```

**Comment by Oliver-Zimmerman** [comment]
Update to 2.0.0 or higher. Thanks
